- name: configure user component
  hosts: user 
  become: yes
  tasks:
  - name: disble nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: upgrade openssl packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
  - openssl
  - openssl-libs
  - openssh
  - openssh-server
  - openssh-clients

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory      

  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      home: /app
      system: true

  - name: download user component code  
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip  
      dest: /tmp/user.zip


  - name: extract user code
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes  


  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy user service file
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service  

  - name: systemctl deamon reload
    ansible.builtin.systemd_service:   
      daemon_reload: true   

  - name: start and enable user
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes    


